<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mini_pupper_bringup</name>
  <version>2.0.0</version>
  <description>Mini Pupper bringup launch files and configuration</description>
  <maintainer email="info@mangdang.net">MangDang</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>mini_pupper_description</exec_depend>
  <exec_depend>mini_pupper_driver</exec_depend>
  <exec_depend>mini_pupper_navigation</exec_depend>
  <exec_depend>mini_pupper_slam</exec_depend>
  <exec_depend>mini_pupper_teleop</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
