slam_toolbox:
  ros__parameters:
    use_sim_time: False
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint
    publish_tf: true
    scan_topic: /scan
    mode: mapping

    enable_interactive_mode: true
    
    tf_buffer_duration: 30.0
    transform_publish_period: 0.1
    transform_timeout: 0.3
    
    map_update_interval: 2.0
    min_time_interval: 0.2
    
    scan_queue_size: 50
    scan_buffer_size: 25
    scan_buffer_maximum_scan_distance: 2.0
    
    max_laser_range: 1.0 # 3.0 later
    minimum_laser_range: 0.03
    
    resolution: 0.02
    
    distance_variance_penalty: 1.0
    angle_variance_penalty: 1.5
    minimum_distance_penalty: 0.05
    minimum_angle_penalty: 0.15
    
    use_response_expansion: true
    do_loop_closing: true
    loop_match_minimum_chain_size: 6
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.45
    loop_match_minimum_response_fine: 0.55
    
    link_match_minimum_response_fine: 0.12
    link_scan_maximum_distance: 2.0
    
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.03
    
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.1
    
    scan_matcher_type: "CORRELATIVE"
    use_scan_matching: true
    use_scan_barycenter: true
    
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    ceres_preconditioner: "SCHUR_JACOBI"
    ceres_trust_strategy: "LEVENBERG_MARQUARDT"
    ceres_dogleg_type: "TRADITIONAL_DOGLEG"
    ceres_loss_function: "HuberLoss"
    
    loop_search_space_dimension: 5.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    loop_search_maximum_distance: 2.0
