slam_toolbox:
  ros__parameters:
    # Core frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    
    # Topics
    scan_topic: /scan
    scan_queue_size: 30
    
    # Mode
    mode: localization
    
    # TF
    publish_tf: true
    transform_publish_period: 0.02
    tf_buffer_duration: 30.0
    transform_timeout: 0.5
    
    # Map
    resolution: 0.05
    max_laser_range: 20.0
    
    # Localization specific
    use_scan_matching: true
    use_scan_barycenter: true