slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    imu_topic: /imu/data
    mode: localization
    publish_tf: true
    resolution: 0.05
    transform_timeout: 0.2
    map_update_interval: 5.0
    enable_interactive_mode: true