/**:
  ros__parameters:
    joints_map:
      left_front:
        - base_lf1
        - lf1_lf2
        - lf2_lf3
        - lf3_lffoot

      right_front:
        - base_rf1
        - rf1_rf2
        - rf2_rf3
        - rf3_rffoot

      left_hind:
        - base_lb1
        - lb1_lb2
        - lb2_lb3
        - lb3_lbfoot

      right_hind:
        - base_rb1
        - rb1_rb2
        - rb2_rb3
        - rb3_rbfoot