/**:
  ros__parameters:
    links_map:
      base: base_link
      left_front:
        - lf1
        - lf2
        - lf3
        - lffoot

      right_front:
        - rf1
        - rf2
        - rf3
        - rffoot

      left_hind:
        - lb1
        - lb2
        - lb3
        - lbfoot

      right_hind:
        - rb1
        - rb2
        - rb3
        - rbfoot