name: Bug Report
description: Create a report to help us fix issues.
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
      
      Before filing, please check if the issue already exists (either open or closed) by using the search bar on the issues page. If it does, comment there.
- type: textarea
  id: reproduction-steps
  attributes:
    label: Reproduction steps
    description: Tell us what you did!
    placeholder: "1. Flashed xxxxx.img to the SD card \n2. Something you did next ..."
  validations:
    required: true
- type: textarea
  id: actual-results
  attributes:
    label: Actual results
    description: What happens after the above steps have been followed? 
  validations:
    required: true
- type: textarea
  id: expected-results
  attributes:
    label: Expected results
    description: Also tell us, what did you expect to happen?
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version of Mini Pupper are you running?
    options:
      - Simulator
      - Mini Pupper
      - Mini Pupper 2
      - Mini Pupper 2 Pro
      - Others
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mangdangroboticsclub/mini_pupper_ros/blob/ros2/CODE_OF_CONDUCT.md)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
