gazebo_ros2_control:
  ros__parameters:
    pid_gains:
      position:
        base_lf1: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
        lf1_lf2: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
        lf2_lf3: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
        base_rf1: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
        rf1_rf2: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
        rf2_rf3: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
        base_lb1: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
        lb1_lb2: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
        lb2_lb3: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
        base_rb1: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
        rb1_rb2: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
        rb2_rb3: {kp: 1.0, kd: 0.2, ki: 0.0, max_integral_error: 0.0, min_integral_error: 0.0}
