<?xml version="1.0"?>
<package format="3">
  <name>mini_pupper_tracking</name>
  <version>0.0.0</version>
  <description>Mini Pupper tracking package</description>
  <maintainer email="kishangrewal06@gmail.com">kishan</maintainer>
  <license>Apache 2.0</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>flask</depend>
  <depend>onnxruntime</depend>

  <!-- New dependencies -->
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
    <ament_export_launch>launch</ament_export_launch>
    <ros_export_launch>launch</ros_export_launch>
  </export>
</package>