<?xml version="1.0"?>
<package format="3">
  <name>mini_pupper_fleet</name>
  <version>0.0.1</version>
  <description>Mini Pupper Fleet package</description>

  <maintainer email="kishangrewal06@gmail.com">kishan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2</depend>

  <build_depend>eigen</build_depend>
  <exec_depend>eigen</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
