string file_name  # The name of the song file
float32 start_second  # Optional offset (in seconds) to start loading the audio file
float32 duration  # Optional duration to be played
---
bool success  # Indicates whether the command was executed successfully
string message  # Additional information or error message